#pragma once

#include "ZString.h"
#include "TArrayRef.h"

enum class ECompiledBehaviorType
{
	BT_ConditionScope = 0,
	BT_Random = 1,
	BT_Match = 2,
	BT_Sequence = 3,
	BT_BEHAVIORS_BEGIN = 4,
	BT_Dummy = 4,
	BT_Dummy2 = 5,
	BT_Error = 6,
	BT_Wait = 7,
	BT_WaitBasedOnDistanceToTarget = 8,
	BT_WaitForItemHandled = 9,
	BT_AbandonOrder = 10,
	BT_CompleteOrder = 11,
	BT_PlayAct = 12,
	BT_PlayReaction = 13,
	BT_SimpleReaction = 14,
	BT_SituationAct = 15,
	BT_SituationApproach = 16,
	BT_SituationGetHelp = 17,
	BT_SituationFace = 18,
	BT_SituationConversation = 19,
	BT_Holster = 20,
	BT_SpeakWait = 21,
	BT_Pickup = 22,
	BT_Drop = 23,
	BT_MoveTo = 24,
	BT_Reposition = 25,
	BT_SituationMoveTo = 26,
	BT_FormationMove = 27,
	BT_SituationJumpTo = 28,
	BT_AmbientWalk = 29,
	BT_AmbientStand = 30,
	BT_CrowdAmbientStand = 31,
	BT_AmbientItemUse = 32,
	BT_AmbientLook = 33,
	BT_Act = 34,
	BT_Patrol = 35,
	BT_MoveToPosition = 36,
	BT_AlertedStand = 37,
	BT_AlertedDebug = 38,
	BT_AttentionToPerson = 39,
	BT_CuriousInvestigate = 40,
	BT_CuriousIdle = 41,
	BT_InvestigateWeapon = 42,
	BT_DeliverWeapon = 43,
	BT_RecoverUnconscious = 44,
	BT_GetOutfit = 45,
	BT_RadioCall = 46,
	BT_EscortOut = 47,
	BT_CautiousSearchPosition = 48,
	BT_LockdownWarning = 49,
	BT_WakeUpUnconscious = 50,
	BT_DeadBodyInvestigate = 51,
	BT_GuardDeadBody = 52,
	BT_DragDeadBody = 53,
	BT_CuriousBystander = 54,
	BT_StandOffArrest = 55,
	BT_StandOffReposition = 56,
	BT_StandAndAim = 57,
	BT_CloseCombat = 58,
	BT_MoveToCloseCombat = 59,
	BT_MoveAwayFromCloseCombat = 60,
	BT_Fight = 61,
	BT_CoverFight = 62,
	BT_ShootFromPosition = 63,
	BT_StandAndShoot = 64,
	BT_HoldCoverPosition = 65,
	BT_CheckLastPosition = 66,
	BT_ProtoCombatHandleHumanShield = 67,
	BT_ProtoSearchIdle = 68,
	BT_ProtoApproachSearchArea = 69,
	BT_ProtoSearchPosition = 70,
	BT_ShootTarget = 71,
	BT_TriggerAlarm = 72,
	BT_MoveInCover = 73,
	BT_MoveToCover = 74,
	BT_AgitatedPatrol = 75,
	BT_AgitatedGuard = 76,
	BT_HeroEscort = 77,
	BT_Escort = 78,
	BT_EscortFormation = 79,
	BT_EscortSearch = 80,
	BT_LeadEscort = 81,
	BT_LeadEscort2 = 82,
	BT_AimReaction = 83,
	BT_FollowHitman = 84,
	BT_RideTheLightning = 85,
	BT_Scared = 86,
	BT_Flee = 87,
	BT_AgitatedBystander = 88,
	BT_SentryFrisk = 89,
	BT_SentryIdle = 90,
	BT_SentryWarning = 91,
	BT_SentryCheckItem = 92,
	BT_VIPScared = 93,
	BT_VIPSafeRoomTrespasser = 94,
	BT_DefendVIP = 95,
	BT_CautiousVIP = 96,
	BT_CautiousGuardVIP = 97,
	BT_Smart = 98,
	BT_SpeakTest = 99,
	BT_Conversation = 100,
	BT_RunToHelp = 101,
	BT_BEHAVIORS_END = 102,
	BT_COMMANDS_BEGIN = 103,
	BT_RenewEvent = 103,
	BT_ExpireEvent = 104,
	BT_SetEventHandled = 105,
	BT_RenewSharedEvent = 106,
	BT_ExpireSharedEvent = 107,
	BT_ExpireAllEvents = 108,
	BT_CreateOrJoinSituation = 109,
	BT_JoinSituation = 110,
	BT_JoinSituationWithActor = 111,
	BT_LeaveSituation = 112,
	BT_GotoPhase = 113,
	BT_RenewGoal = 114,
	BT_ExpireGoal = 115,
	BT_RenewGoalOf = 116,
	BT_SetTension = 117,
	BT_TriggerSpotted = 118,
	BT_CopyKnownLocation = 119,
	BT_UpdateKnownLocation = 120,
	BT_Speak = 121,
	BT_Log = 122,
	BT_COMMANDS_END = 123,
	BT_Invalid = 124,
};

enum class ECompiledConditionType
{
	CT_IsCurrent = 0,
	CT_Current = 1,
	CT_IsExpired = 2,
	CT_HasGoal = 3,
	CT_HasUnhandledGoal = 4,
	CT_MaxActorsWithGoal = 5,
	CT_MinExpired = 6,
	CT_MaxExpired = 7,
	CT_MinAge = 8,
	CT_MaxAge = 9,
	CT_IsSharedOlder = 10,
	CT_IsSharedEventCurrent = 11,
	CT_SharedEventCurrent = 12,
	CT_IsSharedEventExpired = 13,
	CT_MinSharedEventExpired = 14,
	CT_MaxSharedEventExpired = 15,
	CT_MinSharedEventAge = 16,
	CT_MaxSharedEventAge = 17,
	CT_IsNull = 18,
	CT_IsEqual = 19,
	CT_IsOfType = 20,
	CT_IsOfActorType = 21,
	CT_IsOfActorRank = 22,
	CT_IsOfActorRole = 23,
	CT_IsActorRoleBodyguard = 24,
	CT_IsActorRoleVIP = 25,
	CT_HasTension = 26,
	CT_HasTensionOrHigher = 27,
	CT_IsAIModified = 28,
	CT_HasSameOutfit = 29,
	CT_IsLegal = 30,
	CT_IsItemLegalOnHitman = 31,
	CT_IsItemIllegalOnHitman = 32,
	CT_IsItemSuspiciousOnHitman = 33,
	CT_AreVisibleItemsLegal = 34,
	CT_AreVisibleItemsIllegal = 35,
	CT_AreVisibleItemsSuspicious = 36,
	CT_AreVisibleWeaponsLegal = 37,
	CT_AreVisibleWeaponsIllegal = 38,
	CT_AreVisibleWeaponsSuspicious = 39,
	CT_OnlyLegalWeaponsDropped = 40,
	CT_IllegalWeaponDropped = 41,
	CT_SuspiciousWeaponDropped = 42,
	CT_OnlyLegalItemsDropped = 43,
	CT_IllegalItemDropped = 44,
	CT_SuspiciousItemDropped = 45,
	CT_OnlyLegalWeaponsPickedUp = 46,
	CT_IllegalWeaponPickedUp = 47,
	CT_SuspiciousWeaponPickedUp = 48,
	CT_OnlyLegalItemsPickedUp = 49,
	CT_IllegalItemPickedUp = 50,
	CT_SuspiciousItemPickedUp = 51,
	CT_MinDistance = 52,
	CT_MaxDistance = 53,
	CT_MinActualDistance = 54,
	CT_MaxActualDistance = 55,
	CT_ActualInsideSlice = 56,
	CT_MaxDistanceToKnownPosition = 57,
	CT_InSituation = 58,
	CT_SituationTarget = 59,
	CT_SituationHuntTarget = 60,
	CT_IsSituationTarget = 61,
	CT_SituationFromActors = 62,
	CT_SituationFromTarget = 63,
	CT_MaxSituationAge = 64,
	CT_MinSituationAge = 65,
	CT_InPhase = 66,
	CT_MinPhaseAge = 67,
	CT_MaxPhaseAge = 68,
	CT_IsOrderInvalid = 69,
	CT_IsSituationOlderThanSharedEvent = 70,
	CT_HasOrder = 71,
	CT_HasPendingOrder = 72,
	CT_Breakpoint = 73,
	CT_Cooldown = 74,
	CT_Trigger = 75,
	CT_IsInSniperIsland = 76,
	CT_SituationIsType = 77,
	CT_IntRuntimeParamEqualsTo = 78,
	CT_IsCombatDisabled = 79,
	CT_CanJoinSituation = 80,
};

enum class EBehaviorTreeVariableType
{
	BTVT_Invalid = -1,
	BTVT_SceneReference = 0,
	BTVT_Contextual = 1,
	BTVT_Dynamic = 2,
	BTVT_NumTypes = 3,
};

struct SBehaviorBase
{
	ECompiledBehaviorType eBehaviorType;
};

class ZBehaviorTreeVariable
{
	EBehaviorTreeVariableType m_eType;
	unsigned int m_nIndex;
};

struct SConditionBase
{
	ECompiledConditionType eConditionType;
	unsigned int nConditionModifiers;
	ZBehaviorTreeVariable assignTo;
};

struct SConditionScope : SBehaviorBase
{
	SBehaviorBase* pChild;
	SBehaviorBase* pSibling;
	TArrayRef<SConditionBase*> conditions;
};

class ZCompiledBehaviorTree
{
	SConditionScope m_root;
	SBehaviorBase* m_pEnd;
	TArrayRef<ZString> m_sceneReferenceNames;
};
